version: "3"

services:

  proxy:
    build:
      context: nginx-proxy
      dockerfile: Dockerfile
    container_name: proxy
    networks:
      - node-network
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: ["node", "index.js"]
    networks:
      - node-network
    volumes: 
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  db:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: db
    tty: true
    networks:
      - node-network

networks:
  node-network:
    driver: bridge